{
  "language": "elixir",
  "sudo": false,
  "before_script": [
    "mix deps.get --only test"
  ],
  "script": [
    "mix test"
  ],
  "group": "stable",
  "dist": "precise",
  "elixir": "1.3.2",
  "otp_release": 19,
  "os": "linux"
}