language: elixir
env:
  - MIX_ENV=test
elixir:
  - 1.3.2
otp_release:
  - 19.0
services:
  - mongodb
sudo: required
before_script:
  - sleep 15
  - mix deps.get --only test
  # - mix run apps/rumbl/priv/repo/seeds.exs
  # - mix run apps/rumbl/priv/repo/backend_seeds.exs
script:
  - mix test