language: elixir
env:
- MIX_ENV=test
elixir:
- 1.3.2
otp_release:
- 19.0
services:
- mongodb
sudo: required
before_script:
- sleep 15
- mix deps.get --only test
script:
- mix test
deploy:
  provider: heroku
  app: lit-sierra-65151
  api_key:
    secure: rG21uEAQbxjf/EbOcs801Uyr2Crq/2ZpunL8c6z8SMTu0+IxZL7Rydsmx8D4KP73b0rh7PSTW7P5MY8MFrIbVR8KHoizvQcNT2JuYWc0iq6+G4tqkVz5qgenogu5zzZDmusEF6kEtYAijfej/K89Ft4Pf5ph1BIt3fvqD7ibOv3phXmo3Gtu6jOIseuUEYKkh0FFLHQvCx0OqwBOzkx/5IYVVN+HhvrpJ1MZ9rT9hMCAETR3riFIv0n5nZcv2g/vYPuHaBLb3Gri/w8OqesKIrEKV8eci0BEd60E9sq16+PA5etVlnho/45CzRBL15P4EeaZtajlISmeZ7nG9lB1TtqNJVZ8pgIggqORAt/jOkNYEfU3Z/86zr4V+y+4OaTSNMLbhQZERRQDhDqv5RbFoa3ViaGoCAvk+FWkMhoM1cUg+Ue12KnVgEVEuHBKbRmOT0yY/HVlN8Fmk85D0Ox5Xr/OnTZ8JeMUDJCY8vIIAYYq3cabC4gM/q9aldjtBq2/n1CNP11W0Es3Ohii/AA03ROy1xvZbVa3uk8xUhwKKD1JP3iD7G9mR2BDajQBTNjr93HyzbIhg/hyv0CaqHxvhQOrLB9PczahTwFi7EsH6uBqhIu/Bm4RZUKv87DOJYQ4WOId47uPOhe9Xg/cxPwxQ2D4neAQ9tcIkDn3acF64bE=
